//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Form_TB
    {
        public string Employee_FirstName { get; set; }
        public string Employee_LastName { get; set; }
        public int Employee_Id { get; set; }
        public string Employee_Gender { get; set; }
        public string Employee_Email { get; set; }
        public Nullable<int> Employee_Salary { get; set; }
    }
}
